#!/bin/bash

argv=("$@")
argc=${#argv[@]} 

if [[ $argc == 0 ]]; then
    echo "no arguments"
elif [[ $argc == 1 ]]; then
    if [[ $1  =~ ^[0-9]+$ ]]; then
        echo "This is a number"
    else
        echo "This is not a number"
    fi
else
    echo "arguments"
fi