#!/bin/bash

argv=("$@")
argc=${#argv[@]} 

if [[ $argc == 0 ]]; then
    for ((i = 1; i <= 10; i++)); do
        echo $i
    done
else
    while (("$#")); do
        if [[ $1  =~ ^[0-9]+$ ]]; then
            echo $1
        else
            echo "\"$1\""
        fi
        shift
    done
fi